server:
  port: 9999
  context-path: /api/v1/lott
spring:
  application:
    name: lott-result
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.25:9092
          zk-nodes: 192.168.0.25:2181
          autoAddPartitions: true
          autoCreateTopics: true
          minPartitionCount: 1
      bindings:
        lottDataDrawOutput:
          destination: draw.open.data.topic
          content-type: application/octet-stream
          producer:
            partitionCount: 1
        lottDataDrawInput:
          destination: draw.open.data.topic
          content-type: application/octet-stream
          group: open-lott-data-group
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
      default-binder: kafka
    consul:
      host: 192.168.0.25
      port: 8500
security:
  basic:
    enabled: false
management:
  security:
    enabled: false